# Generated by Django 3.0.4 on 2020-03-23 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('aboutme', models.TextField()),
                ('dob', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phonenum', models.CharField(max_length=20)),
                ('cvlink', models.CharField(max_length=100)),
                ('highschoolname', models.CharField(max_length=20)),
                ('highschooldetails', models.TextField()),
                ('highschoolyear', models.CharField(max_length=20)),
                ('intermediatename', models.CharField(max_length=20)),
                ('intermediatedetails', models.TextField()),
                ('intermediateyear', models.CharField(max_length=20)),
                ('collegename', models.CharField(max_length=20)),
                ('collegedetails', models.TextField()),
                ('collegeyear', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('pdate', models.CharField(max_length=20)),
                ('pdetail', models.TextField()),
                ('puid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=20)),
                ('edate', models.CharField(max_length=20)),
                ('edetail', models.TextField()),
                ('euid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=20)),
                ('adate', models.CharField(max_length=20)),
                ('adetail', models.TextField()),
                ('auid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User')),
            ],
        ),
    ]
