# Generated by Django 3.0.4 on 2020-03-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='sduid',
            new_name='suid',
        ),
        migrations.RemoveField(
            model_name='education',
            name='eddetail',
        ),
        migrations.AddField(
            model_name='education',
            name='eddetails',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
