# Generated by Django 3.0.4 on 2020-03-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collegedetails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='collegename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='collegeyear',
        ),
        migrations.RemoveField(
            model_name='user',
            name='highschooldetails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='highschoolname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='highschoolyear',
        ),
        migrations.RemoveField(
            model_name='user',
            name='intermediatedetails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='intermediatename',
        ),
        migrations.RemoveField(
            model_name='user',
            name='intermediateyear',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edname', models.CharField(max_length=20)),
                ('eddate', models.CharField(max_length=20)),
                ('eddetail', models.TextField()),
                ('eduid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User')),
            ],
        ),
    ]
