# Generated by Django 3.0.4 on 2020-03-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200328_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='edorgname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
