# Generated by Django 3.0.4 on 2020-03-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20200323_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(default='default.png', upload_to='temp'),
        ),
    ]
