# Generated by Django 3.0.4 on 2020-03-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_education_edorgname'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='aorgname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='eorgname',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
