# Generated by Django 3.0.4 on 2020-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_education_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='adetail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='eddetail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='edetail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='pdetail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='aboutme',
            field=models.CharField(max_length=100),
        ),
    ]
