# Generated by Django 3.0.4 on 2020-03-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200325_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default.png', upload_to='temp'),
        ),
    ]
