# Generated by Django 3.0.4 on 2020-03-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20200328_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='pdate',
            new_name='purl',
        ),
    ]
