# Generated by Django 3.0.4 on 2020-03-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20200325_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.CharField(max_length=20)),
                ('sduid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.User')),
            ],
        ),
    ]
