# Generated by Django 3.0.4 on 2020-03-30 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20200330_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
