# Generated by Django 3.0.4 on 2020-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profileimage'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedinlink',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default.png', upload_to='projectsimage'),
        ),
    ]
