# Generated by Django 3.0.4 on 2020-03-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20200325_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill2',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='skill3',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
